# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ingitdb < Formula
  desc "ingitdb – a CLI for a developer-grade, schema-validated, AI-native database whose storage engine is a Git repository."
  homepage "https://ingitdb.com"
  version "0.17.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/ingitdb/ingitdb-cli/releases/download/v0.17.0/ingitdb_0.17.0_linux_amd64.tar.gz"
    sha256 "53c6b584e3395334fa19d56f654aac95a470a4444b697817360e33289c20eb7d"
    define_method(:install) do
      bin.install "ingitdb"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ingitdb/ingitdb-cli/releases/download/v0.17.0/ingitdb_0.17.0_linux_arm64.tar.gz"
    sha256 "3f9a65a17f415cbb3b04ba1738b9011cfbef8d3f9547e0c08d1e03257db4775e"
    define_method(:install) do
      bin.install "ingitdb"
    end
  end

  test do
    system "#{bin}/ingitdb", "--version"
  end
end
