# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ingitdb < Formula
  desc "ingitdb – a CLI for a developer-grade, schema-validated, AI-native database whose storage engine is a Git repository."
  homepage "https://ingitdb.com"
  version "0.16.20"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/ingitdb/ingitdb-cli/releases/download/v0.16.20/ingitdb_0.16.20_linux_amd64.tar.gz"
    sha256 "429f8b5d14255eaa21ca2535d0c3d7a69a270ea1cbca8d56fdacfae88839ce91"
    define_method(:install) do
      bin.install "ingitdb"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ingitdb/ingitdb-cli/releases/download/v0.16.20/ingitdb_0.16.20_linux_arm64.tar.gz"
    sha256 "fa7dcd9a196e0c701c57441cf97461e42064e996f1c67175a546efd0c28c5bee"
    define_method(:install) do
      bin.install "ingitdb"
    end
  end

  test do
    system "#{bin}/ingitdb", "--version"
  end
end
