# This file was generated by GoReleaser. DO NOT EDIT.
cask "ingitdb" do
  name "ingitdb"
  desc "ingitdb – a CLI for a developer-grade, schema-validated, AI-native database whose storage engine is a Git repository."
  homepage "https://ingitdb.com"
  version "0.22.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ingitdb"

  on_macos do
    on_intel do
      url "https://github.com/ingitdb/ingitdb-cli/releases/download/v#{version}/ingitdb_#{version}_darwin_amd64.tar.gz"
      sha256 "e40c2280f107261d29f93559eab602b2be5e902f09a07135311d0ce37deaca6a"
    end
    on_arm do
      url "https://github.com/ingitdb/ingitdb-cli/releases/download/v#{version}/ingitdb_#{version}_darwin_arm64.tar.gz"
      sha256 "e67e6f984052131c3ad3115279c0c4cc2d5f98c10dda27762922d6ca1f9f1a6b"
    end
  end

  # No zap stanza required
end
